# Site settings
title: lipu pi jan Talton
description: A landing page to direct people to connections too me & my communities.
url: https://dalton-wither.github.io
baseurl: ""  # Leave empty for user sites, use "/<repo>" for project sites

# Author info
author:
  name: dalton
  email: daltonwither@gmail.com

# Social links
# social_links:
#  discord:  "https://discord.com/users/dalton_arescentes"
#  matrix:   "https://matrix.to/#/@dalton-wither:matrix.org"
#  revolt:   "https://revolt.chat/u/Dalton_Arescentes#7334"
#  bluesky:  "https://bsky.app/profile/dalton-arescentes.bsky.social"
#  mastodon: "https://mastodon.social/@Arescentes"
#  email:    "mailto:daltonwither+pages@gmail.com"

# Theme settings
# theme: jekyll-theme-midnight
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Markdown options
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
